<%
  iaas_list = %w(gcp vsphere vsphere-lb gcp-lb aws-lb openstack-lb)
%>
---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: git-kubo-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf-experimental/kubo-ci
    branch: master

- name: git-kubo-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/kubo-deployment
    branch: master

- name: git-kubo-release
  type: pull-request
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-release
    repo: cloudfoundry-incubator/kubo-release
    base: master
    private_key: ((git-ssh-key))
    access_token: ((github-token-key))

<% iaas_list.each do |iaas| %>
- name: kubo-lock-<%= iaas %>
  type: pool
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-locks.git
    branch: master
    private_key: ((git-ssh-key))
    pool: kubo-<%= iaas %>
<% end %>

- name: gcs-bosh-state
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    versioned_file: bosh/state.json

- name: gcs-bosh-creds
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    versioned_file: bosh/creds.yml

- name: gcs-kubo-release-tarball
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    versioned_file: release-pr/kubo-release.tgz

- name: kubo-version
  type: semver
  source:
    key: kubo-version
    access_key_id: ((gcs-access-key-id))
    secret_access_key: ((gcs-secret-access-key))
    bucket: kubo-pipeline-store
    region_name: us-east1
    endpoint: storage.googleapis.com

jobs:
- name: run-unit-tests
  plan:
  - get: git-kubo-ci
  - get: git-kubo-deployment
  - get: git-kubo-release
    version: every
    trigger: true
  - put: git-kubo-release
    params:
      path: git-kubo-release
      status: pending
  - task: run-unit-tests
    file: git-kubo-ci/tasks/run-release-unit-tests.yml
    on_failure: &on_failure
      put: git-kubo-release
      params:
        path: git-kubo-release
        status: failure

- name: build-kubo-release
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-deployment
      trigger: true
      passed: [ 'run-unit-tests' ]
    - get: kubo-version
    - get: git-kubo-release
      passed: [ 'run-unit-tests' ]
      trigger: true
  - put: git-kubo-release
    params:
      path: git-kubo-release
      status: pending
  - task: build-kubo-release
    file: git-kubo-ci/tasks/build-kubo-release.yml
    on_failure: *on_failure
  - put: gcs-kubo-release-tarball
    params:
      file: kubo-release/kubo-release-*.tgz

<% iaas_list.each do |iaas| %>
- name: claim-lock-<%= iaas %>
  plan:
  - aggregate:
    - get: git-kubo-release
      version: every
      trigger: true
      passed: [ 'build-kubo-release' ]
    - get: git-kubo-deployment
      passed: [ 'build-kubo-release' ]
    - get: gcs-kubo-release-tarball
      passed: [ 'build-kubo-release' ]
  - put: git-kubo-release
    params:
      path: git-kubo-release
      status: pending
  - put: kubo-lock-<%= iaas %>
    params: { acquire: true }
    on_failure: &on_failure_<%= iaas %>
      put: git-kubo-release
      params:
        path: git-kubo-release
        status: failure

- name: install-bosh-<%= iaas %>
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-deployment
      passed: [ 'claim-lock-<%= iaas %>' ]
    - get: kubo-lock-<%= iaas %>
      version: every
      trigger: true
      passed: [ 'claim-lock-<%= iaas %>' ]
    - get: git-kubo-release
      passed: [ 'claim-lock-<%= iaas %>' ]
    - get: gcs-kubo-release-tarball
      passed: [ 'claim-lock-<%= iaas %>' ]
  - put: git-kubo-release
    params:
      path: git-kubo-release
      status: pending
  - task: install
    tags: [<%= iaas %>]
    file: git-kubo-ci/tasks/install-bosh.yml
    input_mapping: {kubo-lock: kubo-lock-<%= iaas %>}
    on_failure: *on_failure_<%= iaas %>

  - aggregate:
    - put: gcs-bosh-creds
      params:
        file: bosh-creds/creds.yml
    - put: gcs-bosh-state
      params:
        file: bosh-state/state.json

- name: deploy-k8s-<%= iaas %>
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: kubo-lock-<%= iaas %>
      trigger: true
      version: every
      passed: [ 'install-bosh-<%= iaas %>' ]
    - get: git-kubo-deployment
      passed: [ 'install-bosh-<%= iaas %>' ]
    - get: git-kubo-release
      passed: [ 'install-bosh-<%= iaas %>' ]
    - get: gcs-bosh-state
      passed: [ 'install-bosh-<%= iaas %>' ]
    - get: gcs-bosh-creds
      passed: [ 'install-bosh-<%= iaas %>' ]
    - get: gcs-kubo-release-tarball
      passed: [ 'install-bosh-<%= iaas %>' ]
  - put: git-kubo-release
    params:
      path: git-kubo-release
      status: pending
  - task: deploy
    tags: [<%= iaas %>]
    file: git-kubo-ci/tasks/deploy-k8s-instance.yml
    input_mapping: {kubo-lock: kubo-lock-<%= iaas %>}
    on_failure: *on_failure_<%= iaas %>

- name: run-k8s-integration-tests-<%= iaas %>
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: kubo-lock-<%= iaas %>
      trigger: true
      version: every
      passed: [ 'deploy-k8s-<%= iaas %>' ]
    - get: git-kubo-deployment
      passed: [ 'deploy-k8s-<%= iaas %>' ]
    - get: gcs-bosh-state
      passed: [ 'deploy-k8s-<%= iaas %>' ]
    - get: gcs-bosh-creds
      passed: [ 'deploy-k8s-<%= iaas %>' ]
    - get: git-kubo-release
      passed: [ 'deploy-k8s-<%= iaas %>' ]
  - put: git-kubo-release
    params:
      path: git-kubo-release
      status: pending
  - task: integration-tests
    tags: [<%= iaas %>]
    file: git-kubo-ci/tasks/run-k8s-integration-tests-ci.yml
    input_mapping: {kubo-lock: kubo-lock-<%= iaas %>}
    on_failure: *on_failure_<%= iaas %>
  - task: pod-to-pod
    tags: [<%= iaas %>]
    file: git-kubo-ci/tasks/pod-to-pod.yml
    input_mapping: {kubo-lock: kubo-lock-<%= iaas %>}
    on_failure: *on_failure_<%= iaas %>
  - task: pv-pod-to-pod
    tags: [<%= iaas %>]
    file: git-kubo-ci/tasks/pv-pod-to-pod.yml
    input_mapping: {kubo-lock: kubo-lock-<%= iaas %>}
    on_failure: *on_failure_<%= iaas %>

- name: destroy-k8s-<%= iaas %>
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: kubo-lock-<%= iaas %>
      trigger: true
      version: every
      passed: [ 'run-k8s-integration-tests-<%= iaas %>' ]
    - get: git-kubo-deployment
      passed: [ 'run-k8s-integration-tests-<%= iaas %>' ]
    - get: gcs-bosh-state
      passed: [ 'run-k8s-integration-tests-<%= iaas %>' ]
    - get: gcs-bosh-creds
      passed: [ 'run-k8s-integration-tests-<%= iaas %>' ]
    - get: git-kubo-release
      passed: [ 'run-k8s-integration-tests-<%= iaas %>' ]
  - put: git-kubo-release
    params:
      path: git-kubo-release
      status: pending
  - task: destroy-k8s
    tags: [<%= iaas %>]
    file: git-kubo-ci/tasks/destroy-k8s-instance.yml
    input_mapping: {kubo-lock: kubo-lock-<%= iaas %>}
    on_failure: *on_failure_<%= iaas %>

- name: destroy-bosh-<%= iaas %>
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-deployment
      passed: [ 'destroy-k8s-<%= iaas %>' ]
    - get: kubo-lock-<%= iaas %>
      trigger: true
      version: every
      passed: [ 'destroy-k8s-<%= iaas %>' ]
    - get: gcs-bosh-state
      passed: [ 'destroy-k8s-<%= iaas %>' ]
    - get: gcs-bosh-creds
      passed: [ 'destroy-k8s-<%= iaas %>' ]
    - get: git-kubo-release
      passed: [ 'destroy-k8s-<%= iaas %>' ]
  - put: git-kubo-release
    params:
      path: git-kubo-release
      status: pending
  - task: destroy
    tags: [<%= iaas %>]
    file: git-kubo-ci/tasks/destroy-bosh.yml
    input_mapping: {kubo-lock: kubo-lock-<%= iaas %>}
    on_failure: *on_failure_<%= iaas %>

  - put: kubo-lock-<%= iaas %>
    params: { release: kubo-lock-<%= iaas %> }
  <% end %>

- name: success-notification
  plan:
  - get: git-kubo-ci
  - get: git-kubo-release
    passed: <%= iaas_list.collect { |iaas| "destroy-bosh-#{iaas}" } %>
    trigger: true
  - put: git-kubo-release
    params:
      path: git-kubo-release
      status: success
