<%
  iaas_list = %w(gcp vsphere)
%>
---
groups:
- name: all
  jobs:
<% iaas_list.each do |iaas| %>
  - claim-lock-<%= iaas %>
  - install-bosh-<%= iaas %>
  - deploy-proxy-<%= iaas %>
  - apply-runtime-config-<%= iaas %>
  - deploy-k8s-<%= iaas %>
  - run-k8s-integration-tests-<%= iaas %>
  - destroy-k8s-<%= iaas %>
  - destroy-proxy-<%= iaas %>
  - destroy-bosh-<%= iaas %>
<% end %>
<% iaas_list.each do |iaas| %>
- name: <%= iaas %>
  jobs:
  - claim-lock-<%= iaas %>
  - install-bosh-<%= iaas %>
  - deploy-proxy-<%= iaas %>
  - apply-runtime-config-<%= iaas %>
  - deploy-k8s-<%= iaas %>
  - run-k8s-integration-tests-<%= iaas %>
  - destroy-k8s-<%= iaas %>
  - destroy-proxy-<%= iaas %>
  - destroy-bosh-<%= iaas %>
<% end %>

resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:

- name: git-kubo-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf-experimental/kubo-ci
    branch: master

<% iaas_list.each do |iaas| %>
- name: kubo-lock-<%= iaas %>
  type: pool
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-locks.git
    branch: master
    private_key: ((git-ssh-key))
    pool: kubo-<%= iaas %>
<% end %>

- name: gcs-bosh-state
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    versioned_file: bosh/state.json


# Creds
- name: gcs-bosh-creds
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    versioned_file: bosh/creds.yml

# Source Artifacts - to be tested
- name: gcs-kubo-release-pre
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-public
    versioned_file: kubo-release-latest.tgz

- name: gcs-kubo-deployment-pre
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-public
    versioned_file: kubo-deployment-latest.tgz

############################################
# Jobs
############################################
jobs:

<% iaas_list.each do |iaas| %>
- name: claim-lock-<%= iaas %>
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: gcs-kubo-release-pre
      trigger: true
    - get: gcs-kubo-deployment-pre
  - put: kubo-lock-<%= iaas %>
    params: { acquire: true }

- name: install-bosh-<%= iaas %>
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: gcs-kubo-release-pre
      passed: [ 'claim-lock-<%= iaas %>' ]
    - get: gcs-kubo-deployment-pre
      passed: [ 'claim-lock-<%= iaas %>' ]
    - get: kubo-lock-<%= iaas %>
      version: every
      trigger: true
      passed: [ 'claim-lock-<%= iaas %>' ]

  - task: unpack-kubo-deployment
    file: git-kubo-ci/tasks/unpack-kubo-deployment.yml
    tags: [<%= iaas %>]

  - task: install
    file: git-kubo-ci/tasks/install-bosh.yml
    tags: [<%= iaas %>]
    input_mapping: {kubo-lock: kubo-lock-<%= iaas %>}

  - aggregate:
    - put: gcs-bosh-creds
      params:
        file: bosh-creds/creds.yml
    - put: gcs-bosh-state
      params:
        file: bosh-state/state.json

- name: deploy-proxy-<%= iaas %>
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: gcs-bosh-creds
      passed: ['install-bosh-<%= iaas %>']
    - get: kubo-lock-<%= iaas %>
      version: every
      trigger: true
      passed: [ 'install-bosh-<%= iaas %>' ]
    - get: gcs-bosh-state
      passed: [ 'install-bosh-<%= iaas %>' ]
    - get: gcs-kubo-release-pre
      passed: [ 'install-bosh-<%= iaas %>' ]
    - get: gcs-kubo-deployment-pre
      passed: [ 'install-bosh-<%= iaas %>' ]

  - task: unpack-kubo-deployment
    file: git-kubo-ci/tasks/unpack-kubo-deployment.yml
    tags: [<%= iaas %>]

  - task: deploy-tinyproxy
    file: git-kubo-ci/tasks/deploy-tinyproxy.yml
    tags: [<%= iaas %>]
    input_mapping: {kubo-lock: kubo-lock-<%= iaas %>}
    params:
      IAAS: "<%=iaas%>"

- name: apply-runtime-config-<%= iaas %>
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: kubo-lock-<%= iaas %>
      version: every
      trigger: true
      passed: [ 'deploy-proxy-<%= iaas %>' ]
    - get: gcs-kubo-deployment-pre
      passed: [ 'deploy-proxy-<%= iaas %>' ]
    - get: gcs-kubo-release-pre
      passed: [ 'deploy-proxy-<%= iaas %>' ]
    - get: gcs-bosh-state
      passed: [ 'deploy-proxy-<%= iaas %>' ]
    - get: gcs-bosh-creds
      passed: [ 'deploy-proxy-<%= iaas %>' ]

  - task: apply-runtime-config
    file: git-kubo-ci/tasks/apply-runtime-config.yml
    tags: [<%= iaas %>]
    input_mapping: {kubo-lock: kubo-lock-<%= iaas %>}

- name: deploy-k8s-<%= iaas %>
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: kubo-lock-<%= iaas %>
      version: every
      trigger: true
      passed: [ 'apply-runtime-config-<%= iaas %>' ]
    - get: gcs-kubo-deployment-pre
      passed: [ 'apply-runtime-config-<%= iaas %>' ]
    - get: gcs-kubo-release-pre
      passed: [ 'apply-runtime-config-<%= iaas %>' ]
    - get: gcs-bosh-state
      passed: [ 'apply-runtime-config-<%= iaas %>' ]
    - get: gcs-bosh-creds
      passed: [ 'apply-runtime-config-<%= iaas %>' ]

  - task: unpack-kubo-deployment
    file: git-kubo-ci/tasks/unpack-kubo-deployment.yml
    tags: [<%= iaas %>]

  - task: apply-proxy-to-env
    file: git-kubo-ci/tasks/apply-proxy-to-env.yml
    tags: [<%= iaas %>]
    input_mapping: {kubo-lock: kubo-lock-<%= iaas %>}

  - task: deploy
    tags: [<%= iaas %>]
    input_mapping:
      gcs-kubo-release-tarball: gcs-kubo-release-pre
      kubo-lock: kubo-lock-with-proxy
    file: git-kubo-ci/tasks/deploy-k8s-instance.yml


- name: run-k8s-integration-tests-<%= iaas %>
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: kubo-lock-<%= iaas %>
      version: every
      trigger: true
      passed: [ 'deploy-k8s-<%= iaas %>' ]
    - get: gcs-bosh-state
      passed: [ 'deploy-k8s-<%= iaas %>' ]
    - get: gcs-bosh-creds
      passed: [ 'deploy-k8s-<%= iaas %>' ]
    - get: gcs-kubo-release-pre
      passed: [ 'deploy-k8s-<%= iaas %>' ]
    - get: gcs-kubo-deployment-pre
      passed: [ 'deploy-k8s-<%= iaas %>' ]

  - task: unpack-kubo-deployment
    file: git-kubo-ci/tasks/unpack-kubo-deployment.yml
    tags: [<%= iaas %>]

  - task: integration-tests
    file: git-kubo-ci/tasks/run-k8s-integration-tests-ci.yml
    tags: [<%= iaas %>]
    input_mapping: {kubo-lock: kubo-lock-<%= iaas %>}

  - task: pod-to-pod
    file: git-kubo-ci/tasks/pod-to-pod.yml
    tags: [<%= iaas %>]
    input_mapping: {kubo-lock: kubo-lock-<%= iaas %>}

- name: destroy-k8s-<%= iaas %>
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: kubo-lock-<%= iaas %>
      version: every
      trigger: true
      passed: [ 'run-k8s-integration-tests-<%= iaas %>' ]
    - get: gcs-kubo-deployment-pre
      passed: [ 'run-k8s-integration-tests-<%= iaas %>' ]
    - get: gcs-kubo-release-pre
      passed: [ 'run-k8s-integration-tests-<%= iaas %>' ]
    - get: gcs-bosh-state
      passed: [ 'run-k8s-integration-tests-<%= iaas %>' ]
    - get: gcs-bosh-creds
      passed: [ 'run-k8s-integration-tests-<%= iaas %>' ]

  - task: unpack-kubo-deployment
    file: git-kubo-ci/tasks/unpack-kubo-deployment.yml
    tags: [<%= iaas %>]

  - task: destroy-k8s
    file: git-kubo-ci/tasks/destroy-k8s-instance.yml
    tags: [<%= iaas %>]
    input_mapping: {kubo-lock: kubo-lock-<%= iaas %>}


- name: destroy-proxy-<%= iaas %>
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: gcs-kubo-deployment-pre
      passed: [ 'run-k8s-integration-tests-<%= iaas %>' ]
    - get: gcs-bosh-creds
      passed: [ 'run-k8s-integration-tests-<%= iaas %>' ]
    - get: kubo-lock-<%= iaas %>
      version: every
      trigger: true
      passed: [ 'run-k8s-integration-tests-<%= iaas %>' ]

  - task: unpack-kubo-deployment
    file: git-kubo-ci/tasks/unpack-kubo-deployment.yml
    tags: [<%= iaas %>]
  - task: destroy-tinyproxy
    tags: [<%= iaas %>]
    file: git-kubo-ci/tasks/destroy-tinyproxy.yml
    input_mapping: {kubo-lock: kubo-lock-<%= iaas %>}

- name: destroy-bosh-<%= iaas %>
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: kubo-lock-<%= iaas %>
      version: every
      trigger: true
      passed:
      - 'destroy-proxy-<%= iaas %>'
      - 'destroy-k8s-<%= iaas %>'
    - get: gcs-kubo-deployment-pre
      passed:
      - 'destroy-proxy-<%= iaas %>'
      - 'destroy-k8s-<%= iaas %>'
    - get: gcs-kubo-release-pre
      passed: [ 'destroy-k8s-<%= iaas %>' ]
    - get: gcs-bosh-state
      passed: [ 'destroy-k8s-<%= iaas %>' ]
    - get: gcs-bosh-creds
      passed:
      - 'destroy-proxy-<%= iaas %>'
      - 'destroy-k8s-<%= iaas %>'

  - task: unpack-kubo-deployment
    tags: [<%= iaas %>]
    file: git-kubo-ci/tasks/unpack-kubo-deployment.yml

  - task: destroy
    tags: [<%= iaas %>]
    file: git-kubo-ci/tasks/destroy-bosh.yml
    input_mapping: {kubo-lock: kubo-lock-<%= iaas %>}

  - put: kubo-lock-<%= iaas %>
    params: { release: kubo-lock-<%= iaas %> }
<% end %>

#
# - name: upload-kubo-deployment
#  serial_groups: [proxy]
#   plan:
#   - aggregate:
#     - get: git-kubo-ci
#     - get: git-kubo-deployment
#       passed: [ destroy-bosh ]
#     - get: kubo-version
#       passed: [ destroy-bosh ]
#       trigger: true
#   - task: create-kubo-deployment-tarball
#     file: git-kubo-ci/tasks/create-kubo-deployment-tarball.yml
#   - aggregate:
#     - put: gcs-kubo-deployment-tarball
#       params:
#         file: tarballs/kubo-deployment-*.tgz
#     - put: gcs-kubo-deployments
#       params:
#         file: tarballs/kubo-deployment-*.tgz
#
#
# - name: upload-kubo-release
#  serial_groups: [proxy]
#   plan:
#   - aggregate:
#     - get: gcs-kubo-release-tarball-untested
#       passed: [ destroy-bosh ]
#     - get: kubo-version
#       passed: [ destroy-bosh ]
#       trigger: true
#   - aggregate:
#     - put: gcs-kubo-release-tarball
#       params:
#         file: gcs-kubo-release-tarball-untested/kubo-release-*.tgz
#     - put: gcs-kubo-releases
#       params:
#         file: gcs-kubo-release-tarball-untested/kubo-release-*.tgz
#
# - name: success-notification
#  serial_groups: [proxy]

#   plan:
#   - aggregate:
#     - get: kubo-version
#       passed: [ upload-kubo-release, upload-kubo-deployment ]
#       trigger: true
#   - put: slack-alert
#     params:
#       silent: true
#       icon_emoji: ":frog:"
#       text: |
#         I am green and it'll do fine, it's beautiful
#         And I think it's what I want to be
