platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/run-k8s-turbulence-tests.sh

inputs:
  - name: git-kubo-ci
  - name: gcs-bosh-creds
  - name: kubo-lock
