---
azs:
- name: z1
  cloud_properties:
    datacenters:
    - clusters: [((vcenter_cluster)): { resource_pool: ((vcenter_rp))}]

networks:
- name: &network_name ((deployments_network))
  type: manual
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    dns: [8.8.8.8]
    azs: [z1]
    cloud_properties:
      name: ((network_name))
    reserved: ((reserved_ips))

vm_types:
- name: worker
  cloud_properties:
    ram: 8192
    cpu: 2
    disk: 102400

disk_types:
- name: 10240
  disk_size: 10240
- name: 5120
  disk_size: 5120

compilation:
  workers: 1
  network: *network_name
  az: z1
  reuse_compilation_vms: true
  vm_type: worker
