---
releases:
- name: turbulence
  version: 0.7
  url: https://bosh.io/d/github.com/cppforlife/turbulence-release?v=0.7
  sha1: 6e9d33e7372925b55a929be6852c10758c0173cb

addons:
- name: turbulence_agent
  jobs:
  - name: turbulence_agent
    release: turbulence
    consumes:
      api:
        instances:
        - address: ((internal_ip))
        properties:
          username: turbulence
          password: ((turbulence_api_password))
          listen_port: 8080
          cert:
            ca: ((turbulence_api_ssl.ca))
