---
releases:
- name: turbulence
  version: 0.6
  url: https://bosh.io/d/github.com/cppforlife/turbulence-release?v=0.6
  sha1: 5222108e2aa500bb60205d7a0e6f654dde391f36

addons:
- name: turbulence_agent
  jobs:
  - name: turbulence_agent
    release: turbulence
    consumes:
      api:
        instances:
        - address: ((internal_ip))
        properties:
          username: turbulence
          password: ((turbulence_api_password))
          listen_port: 8080
          cert:
            ca: ((turbulence_api_ssl.ca))
