instance_groups:
- azs: [z1, z2, z3]
  instances: 1
  jobs:
  - name: postgresql
    release: concourse
  lifecycle: service
  name: db
  networks:
  - name: default
  persistent_disk_type: large
  properties:
    databases:
    - name: atc
      password: ((atc-db-password))
      role: atc
  stemcell: bosh-google-kvm-ubuntu-trusty-go_agent
  update:
    max_in_flight: 1
  vm_type: default
- azs: [z1, z2, z3]
  instances: 1
  jobs:
  - name: atc
    properties:
      allow_self_signed_certificates: true
      github_auth:
        client_id: ((github-client-id))
        client_secret: ((github-client-secret))
        authorize:
          - organization: pivotal-cf-experimental
            teams: [ pcf-kubo ]
          - organization: cloudfoundry-incubator
            teams: [ cf-kubo ]
          - user: johnsonj
          - user: mkjelland
          - user: evandbrown
          - user: erjohnso
      external_url: https://ci.kubo.sh
      postgresql_database: atc
      tls_cert: ((atc-certificate.certificate))((atc-certificate.ca))
      tls_key: ((atc-certificate.private_key))
      tls_bind_port: 443
      bind_port: 80
    release: concourse
  - name: tsa
    properties:
      host_key: ((tsa-host-key.private_key))
      host_public_key: ((tsa-host-key.public_key))
      authorized_keys:
      - ((worker-key.public_key))
    release: concourse
  lifecycle: service
  name: concourse
  networks:
  - default:
    - dns
    - gateway
    name: default
  persistent_disk_type: large
  properties: {}
  stemcell: bosh-google-kvm-ubuntu-trusty-go_agent
  update:
    max_in_flight: 1
  vm_type: default
  vm_extensions:
  - gcp-lb
- azs: [z1, z2, z3]
  instances: 1
  jobs:
  - name: groundcrew
    release: concourse
    consumes:
      baggageclaim: {from: bc-gcp}
    properties:
      tags:
        - gcp
        - gcp-lb
      tsa:
        private_key: ((worker-key.private_key))
  - name: baggageclaim
    release: concourse
    provides:
      baggageclaim: {as: bc-gcp}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_address: 0.0.0.0:7777
        listen_network: tcp
  lifecycle: service
  name: worker-gcp
  networks:
  - name: default
  stemcell: bosh-google-kvm-ubuntu-trusty-go_agent
  update:
    max_in_flight: 1
  vm_type: large
- azs: [z1, z2, z3]
  instances: 2
  jobs:
  - name: groundcrew
    release: concourse
    consumes:
      baggageclaim: {from: bc}
    properties:
      tsa:
        private_key: ((worker-key.private_key))
  - name: baggageclaim
    release: concourse
    provides:
      baggageclaim: {as: bc}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_address: 0.0.0.0:7777
        listen_network: tcp
  lifecycle: service
  name: worker
  networks:
  - name: default
  stemcell: bosh-google-kvm-ubuntu-trusty-go_agent
  update:
    max_in_flight: 1
  vm_type: large
name: kubo-ci
releases:
- name: concourse
  version: 3.3.0
  url: https://bosh.io/d/github.com/concourse/concourse?v=3.3.0
  sha1: f0b5ab73ba26e9cc72c8989d20ae2e8d994f18c4
- name: garden-runc
  version: 1.6.0
  url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.6.0
  sha1: 58fbc64aff303e6d76899441241dd5dacef50cb7
stemcells:
- alias: bosh-google-kvm-ubuntu-trusty-go_agent
  os: ubuntu-trusty
  version: latest
update:
  canaries: 1
  canary_watch_time: 30000-300000
  max_errors: 2
  max_in_flight: 1
  serial: true
  update_watch_time: 30000-300000

variables:
- name: atc-db-password
  type: password
