---
resources:
- name: git-kubo-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf-experimental/kubo-ci
    branch: master
    paths:
    - docker-images/*
- name: test-runner-latest
  type: docker-image
  source:
    repository: pcfkubo/test-runner
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: latest

- name: test-runner-stable
  type: docker-image
  source:
    repository: pcfkubo/test-runner
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: stable

- name: vsphere-cleaner-latest
  type: docker-image
  source:
    repository: pcfkubo/vsphere-cleaner
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: latest

- name: vsphere-cleaner-stable
  type: docker-image
  source:
    repository: pcfkubo/vsphere-cleaner
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: stable

- name: curl-latest
  type: docker-image
  source:
    repository: pcfkubo/curl
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: latest

- name: curl-stable
  type: docker-image
  source:
    repository: pcfkubo/curl
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: stable

- name: aws-maintenance-latest
  type: docker-image
  source:
    repository: pcfkubo/aws-maintenance
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: latest

- name: aws-maintenance-stable
  type: docker-image
  source:
    repository: pcfkubo/aws-maintenance
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: stable

- name: kubo-ci-latest
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: latest

- name: kubo-ci-stable
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: stable
- name: kubectl
  type: docker-image
  source:
    repository: pcfkubo/alpine
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: stable

- name: gcs-vsphere-cleaner
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-public
    versioned_file: vsphere-cleaner

resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

jobs:
- name: build-kubo-ci
  plan:
  - get: git-kubo-ci
    trigger: true
  - put: kubo-ci-latest
    params:
      build: git-kubo-ci/docker-images
      cache: true
  - task: test-docker-image
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/kubo-ci
          tag: latest

      inputs:
      - name: git-kubo-ci
      run:
        path: ginkgo
        args:
        - -r
        - git-kubo-ci/docker-images/system_tests/
  - put: kubo-ci-stable
    params:
      cache: true
      pull_repository: pcfkubo/kubo-ci
      pull_tag: latest

- name: build-vsphere-cleaner
  plan:
  - get: git-kubo-ci
    trigger: true
  - get: gcs-vsphere-cleaner
    trigger: true
  - put: vsphere-cleaner-latest
    params:
      build: git-kubo-ci/docker-images/vsphere-cleaner
  - task: test-docker-image
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/vsphere-cleaner
          tag: latest
      inputs:
      - name: git-kubo-ci
      run:
        path: git-kubo-ci/docker-images/vsphere-cleaner/run_tests
  - put: vsphere-cleaner-stable
    params:
      cache: true
      pull_repository: pcfkubo/vsphere-cleaner
      pull_tag: latest

- name: build-curl
  plan:
  - get: git-kubo-ci
    trigger: true
  - put: curl-latest
    params:
      build: git-kubo-ci/docker-images/curl
  - task: test-docker-image
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/curl
          tag: latest
      inputs:
      - name: git-kubo-ci
      run:
        path: git-kubo-ci/docker-images/curl/run_tests
  - put: curl-stable
    params:
      cache: true
      pull_repository: pcfkubo/curl
      pull_tag: latest

- name: build-test-runner
  plan:
  - get: git-kubo-ci
    trigger: true
  - put: test-runner-latest
    params:
      build: git-kubo-ci/docker-images/test-runner
  - task: test-docker-image
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/test-runner
          tag: latest
      inputs:
      - name: git-kubo-ci
      run:
        path: ginkgo
        args:
        - -r
        - git-kubo-ci/docker-images/test-runner/system_tests
  - put: test-runner-stable
    params:
      cache: true
      pull_repository: pcfkubo/test-runner
      pull_tag: latest

- name: build-kubectl
  plan:
  - get: git-kubo-ci
    trigger: true
  - put: kubectl
    params:
      build: git-kubo-ci/docker-images/kubectl

- name: build-aws-maintenance
  plan:
   - get: git-kubo-ci
     trigger: true
   - put: aws-maintenance-latest
     params:
       build: git-kubo-ci/docker-images/aws-maintenance
   - task: test-docker-image
     config:
       platform: linux
       image_resource:
         type: docker-image
         source:
           repository: pcfkubo/aws-maintenance
           tag: latest
       inputs:
       - name: git-kubo-ci
       run:
         path: git-kubo-ci/docker-images/aws-maintenance/run_tests
   - put: aws-maintenance-stable
     params:
       cache: true
       pull_repository: pcfkubo/aws-maintenance
       pull_tag: latest
